Python script: /home/admin/work/personal/snowflake_sandbox/03_models/01_raw/python/bluesky/extract_feed.py
Log file: /home/admin/work/personal/snowflake_sandbox/03_models/01_raw/python/bluesky/extract_logs//extract_feed_2025-04-08_03-34-57.log
Traceback (most recent call last):
  File "/home/admin/work/personal/snowflake_sandbox/03_models/01_raw/python/bluesky/extract_feed.py", line 395, in <module>
    extract_feed()
  File "/home/admin/work/personal/snowflake_sandbox/03_models/01_raw/python/bluesky/extract_feed.py", line 343, in extract_feed
    cli, session_usr = bluesky_login()
                       ^^^^^^^^^^^^^^^
  File "/home/admin/work/personal/snowflake_sandbox/03_models/01_raw/python/bluesky/extract_feed.py", line 57, in bluesky_login
    bsky_client.login(USR, KEY)
  File "/home/admin/miniconda3/lib/python3.12/site-packages/atproto_client/client/client.py", line 92, in login
    session = self._get_and_set_session(login, password)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/miniconda3/lib/python3.12/site-packages/atproto_client/client/client.py", line 47, in _get_and_set_session
    session = self.com.atproto.server.create_session(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/miniconda3/lib/python3.12/site-packages/atproto_client/namespaces/sync_ns.py", line 5748, in create_session
    response = self._client.invoke_procedure(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/miniconda3/lib/python3.12/site-packages/atproto_client/client/base.py", line 115, in invoke_procedure
    return self._invoke(InvokeType.PROCEDURE, url=self._build_url(nsid), params=params, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/miniconda3/lib/python3.12/site-packages/atproto_client/client/client.py", line 40, in _invoke
    return super()._invoke(invoke_type, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/miniconda3/lib/python3.12/site-packages/atproto_client/client/base.py", line 122, in _invoke
    return self.request.post(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/miniconda3/lib/python3.12/site-packages/atproto_client/request.py", line 181, in post
    return _parse_response(self._send_request('POST', *args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/miniconda3/lib/python3.12/site-packages/atproto_client/request.py", line 171, in _send_request
    _handle_request_errors(e)
  File "/home/admin/miniconda3/lib/python3.12/site-packages/atproto_client/request.py", line 54, in _handle_request_errors
    raise exception
  File "/home/admin/miniconda3/lib/python3.12/site-packages/atproto_client/request.py", line 169, in _send_request
    return _handle_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/miniconda3/lib/python3.12/site-packages/atproto_client/request.py", line 77, in _handle_response
    raise exceptions.UnauthorizedError(error_response)
atproto_client.exceptions.UnauthorizedError: Response(success=False, status_code=401, content=XrpcError(error='AuthenticationRequired', message='Invalid identifier or password'), headers={'date': 'Tue, 08 Apr 2025 07:35:00 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '77', 'connection': 'keep-alive', 'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '10', 'ratelimit-remaining': '9', 'ratelimit-reset': '1744184100', 'ratelimit-policy': '10;w=86400', 'etag': 'W/"4d-98r3hvgolnybv7tgksQiZbSE7Zg"', 'vary': 'Accept-Encoding'})
